### ISSUE TITLE
undefined: ResolveVanityUrl

### ISSUE THREAD

**Issue by Grobycn** [Philipp15b/go-steamapi#10]
`go get github.com/Philipp15b/go-steamapi`
throws error:
`github.com/Philipp15b/go-steamapi/id.go:33:15: undefined: ResolveVanityUrl`

There is a function named `ResolveVanityURL` in `go-steamapi/profiles.go`
Seems case sensitivity mismatch.

edit:
another mismatch
`github.com/Philipp15b/go-steamapi/id.go:38:26: resp.SteamId undefined (type *ResolveVanityURLResponse has no field or method SteamId, but does have SteamID)`

**Comment by Philipp15b** [comment]
I think the problems should have been fixed by #9, which I've now merged. Thank you for the report!
